{% set name = "bytecode" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7263239a8d3f70fc7c303862b20cd2c6788052e37ce0a26e67309d280e985984

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - typing_extensions

test:
  imports:
    - bytecode
    - bytecode.instr
    - bytecode.flags
    - bytecode.concrete
    - bytecode.cfg

about:
  home: https://github.com/vstinner/bytecode
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python module to generate and modify Python bytecode.
  doc_url: https://bytecode.readthedocs.io/
  dev_url: https://github.com/vstinner/bytecode

extra:
  recipe-maintainers:
    - MatthieuDartiailh
    - gabrielcnr
    - marcelotrevisani
