{% set name = "bytecode" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06676a3c3bccc9d3dc73ee625650ea57df2bc117358826f4f290f0e1faa42292

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
    - wheel
    - setuptools_scm >=3.4.3
    # From setuptools_scm[toml]
    - tomli >=1
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - bytecode
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vstinner/bytecode
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python module to generate and modify Python bytecode.
  doc_url: https://bytecode.readthedocs.io/
  dev_url: https://github.com/vstinner/bytecode

extra:
  recipe-maintainers:
    - MatthieuDartiailh
    - gabrielcnr
    - marcelotrevisani
    - thewchan
