travis:
  secure:
    BINSTAR_TOKEN: psJstgUYkzY1y4+c52EmAsYUX13gYrPCAnLbT058GM76RmyGApu7nWiBL/6okficUSCV1oehmNFFbKWTGrnkP+BNwOEdPhW7SZxyFme7R9vyWZz3imtjV736ONH+lidMflEMKrAuXE3smB5p+bbWZ3bpoqtEvdC/97/9DbmPd7eCSX8YoySSDiml7Avzab0e9quuE/0ieHggLFXmKVeFgDjpQSFkzZHE8lKyD64dq7nJSVwdeqxcsxXOUYYDdByF5qFbLWZtWrU2a/00boc3Jy9OcjHi+FhRBcdN6tRRs8C5jo/T4PEUXbTzhWFuoBGAvoFCTnTe7Xk9xSC/EsROmX/J2wKyjsuTO6UFwLgFjrXM9PYWdklR9bhJK9qYqQOaBcNE8jcC+Do9U/e75eeqhIemP6x+f2oFfRSUYOOcZuK6WXJrKnNLkAo7DYxbtDj8Qhnnmyt0ZbBawtlyZ0oqeOzZ237fieS+pYoClpqqLAT4zMqO+uj7R82EYXlL9PwADb7/ZUlELyLZsNkLCn/PF2p1Xg/pcVkjMaj3tMoIBFfK0gOA9WXmGRECJhsx4v+APod7koVB1JonRsrgbXm6oQDWZ+tDJirFK1HG2LdSweDQfBD6nN7X20c3sYk5Lgmo/PBCJTvHqyzO2GUh+vwOhVNPNgBKBSxVuw93UkpzqTo=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
